# Generated by Django 5.2.4 on 2025-08-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_products_food_product'),
        ('OrderManagement', '0002_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
    ]
