# Generated by Django 5.2.4 on 2025-08-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0003_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
