# Generated by Django 5.2.3 on 2025-08-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='food_product',
            field=models.BooleanField(default=False),
        ),
    ]
