# Generated by Django 5.2.4 on 2025-08-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_products_food_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
