# Generated by Django 5.2.8 on 2025-11-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_products_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
    ]
