# Generated by Django 5.2.4 on 2025-08-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'admin'), (1, 'manager'), (2, 'Employee')], default=2),
        ),
    ]
