# Generated by Django 5.2.4 on 2025-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Manager'), (2, 'Employee')], default=2),
        ),
    ]
